### ISSUE TITLE
`*server log*` buffer disappear only under `dap-python`

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/dap-mode#148]
My dap-mode for python is weird. Every time I trigger dap-debug, the *server log* buffer will disappear. And it only happens for dap-python (tested with dap-go, server log buffer doesn't disappear). Here is the config I have.
```
(dap-register-debug-template
 "My App"
 (list :type "python"
       :args ""
       :cwd nil
       :env '(("DEBUG" . "1"))
       :target-module "main.py"
       :request "launch"
       :name "My App"))
```

Any thought on this?

**Comment by yyoncho** [comment]
By server log you mean \*compilation\* buffer? 

If yes, have you tried the latest dap-mode, I think that removing the compilation buffer no longer happens(as a side effect of https://github.com/emacs-lsp/dap-mode/pull/145). Note that dap-python and dap-go work in a different way. In dap-go the content output comes via dap protocol since the process is managed by the debug adapter while in dap-python the process is managed by emacs in the normal compilation buffer and replacing the compilation buffer is what emacs normally does.

**Comment by ztlevi** [comment]
Yes, it's the `*compliation*` buffer.

I'm using the latest dap-mode cuz `straight.el` will pull the master branch.

And you can using this project to debug it. https://github.com/ztlevi/pytest-dap-mode-test

**Comment by ztlevi** [comment]
@yyoncho 
This issue seems not fixed by 7eea7ba. And we need to define `:target-module` rather `:module`, which doesn't seem very consistent with what vscode does. In vscode, it doesn't allow me to define `"target-module":"pytest"`.

Other than that, I found `dap-disconnect` doesn't kill the session's process. 

And how can we define the file I want to run. For example, in vscode, you can define it with `:program` in `launch.json`.

**Comment by yyoncho** [comment]
> This issue seems not fixed by 7eea7ba. 

I think the issue should have been fixed by https://github.com/emacs-lsp/dap-mode/pull/145 , can  you verify that?

> And we need to define :target-module rather :module, which doesn't seem very consistent with what vscode does. In vscode, it doesn't allow me to define "target-module":"pytest".

I unified both dap-mode and vscode with bc67f3cb673e4b84dac3b8110a6f0aaba5d79d7c , you can use :program and :module just like you do in vscode.

> Other than that, I found dap-disconnect doesn't kill the session's process.

You may file another issue for that, I will be addressed separately since it has a workaround(kill the session manually).

**Comment by ztlevi** [comment]
Sorry for the late response, I was travelling in Miami.

This fix looks good so far. I will probly play with dap-python more to see if I still have issue with `dap-disconnect`.

Thank you! 💯
