### ISSUE TITLE
Python: dap-mode hangs on Windows 10

### ISSUE THREAD

**Issue by AlexGalchenko** [emacs-lsp/dap-mode#295]
The debugging process hangs when you trying to debug python code on windows 10.

When I'm trying to debug any python code and execute M-x dap-debug (with Debug current buffer profile), the dap process hangs, and nothing happened. Looks like dap-mode don't event started, any dap-mode command shows me a message:
**LSP :: Currently active thread is not stopped. Use `dap-switch-thread' or select stopped thread from sessions view.**

[Here the screenshot](https://i.imgur.com/bXramDX.png)

The process list show me this:
[The list of processes](https://i.imgur.com/cmZFl1a.png)

After execution, the dap-print-io shows only this:
Sending: 
{
  "command": "initialize",
  "arguments": {
    "clientID": "vscode",
    "clientName": "Visual Studio Code",
    "adapterID": "python",
    "pathFormat": "path",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "supportsVariableType": true,
    "supportsVariablePaging": true,
    "supportsRunInTerminalRequest": true,
    "locale": "en-us"
  },
  "type": "request",
  "seq": 1
}
No other message, but only this ...

So, execute this command from the command line to and see this:

[cmdproxy.exe and python debug](https://i.imgur.com/ActIWyJ.png)

My dap configuration is pretty straightforward. 
(use-package dap-mode
  :ensure
  :diminish
  :hook((lsp-mode     . dap-mode))
  :bind(("<f12>"      . dap-debug)
        ("<f8>"       . dap-continue)
        ("<f9>"       . dap-next)
        ("<M-f11>"    . dap-step-in)
        ("C-M-<f11>"  . dap-step-out)
        ("<f7>"       . dap-breakpoint-toggle))
  :config
  (require 'dap-python)
  (dap-mode 1)
  
  (dap-ui-mode 1)
  (dap-ui-controls-mode -1))

Also, with this configuration dap-mode works perfectly on Linux.

Emacs version: GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13
OS: Windows 10 Pro 1903 18362.836
Python version: 3.8.3
Dap-mode version: dap-mode-20200529.126

As I said before, the same configuration works perfectly on Linux.

**Comment by sebasmonia** [comment]
I'm having the same problem right now...

**Comment by yyoncho** [comment]
I suspect that this is caused by delimiters being `\n\n\n\n` on windows not `\r\n\r\n` but I do not have a windows machine to verify that. I will provide a change in order to verify that.

**Comment by sebasmonia** [comment]
I just setup dap-mode in Linux following the instructions and it worked as expected. I can test on my work machine if you have a candidate fix :)

**Comment by yyoncho** [comment]
Can you test with `(setq inhibit-eol-conversion t) ` globally? see https://github.com/emacs-lsp/dap-mode/issues/214

**Comment by AlexGalchenko** [comment]
It works! 
![image](https://user-images.githubusercontent.com/16255126/85995412-dc7d7100-ba06-11ea-9e6c-32f034218329.png)

But now i'm seeing ^M everywhere.

**Comment by deb75** [comment]
My similar issue (#311) is also fixed with `(setq inhibit-eol-conversion t)`

Regards

**Comment by AlexGalchenko** [comment]
@yyoncho thanks for spending time on this!

**Comment by yyoncho** [comment]
Reopening - this should work OOTB.

**Comment by sebasmonia** [comment]
Didn't work for me until I set `inhibit-eol-conversion`.

**Comment by yyoncho** [comment]
> Didn't work for me until I set `inhibit-eol-conversion`.

I mean that we should make it work out of the box and then close the issue.

**Comment by yyoncho** [comment]
I pushed a fix that fixed the same issue in lsp-mode repo. Please confirm that it works without explicitly setting inhibit-eol-conversion to t.

**Comment by deb75** [comment]
Hi,

After updating all packages to their latest version, it seems `dap-mode` still hangs without setting `inhibit-eol-conversion` to `t`.

However, it is a bit annoying to let this variable to true any time, should it be possible to set this variable to true on the fly when running `dap-java-run-test-method`,  `dap-java-run-test-class` and `dap-debug` and then revert to false, when tests are done ?

Regards

**Comment by yyoncho** [comment]
This is what I am trying to achieve.

**Comment by sebasmonia** [comment]
I just tried it and it worked OK for me on Windows 10. @deb75 are you sure you got latest version? mine is `dap-mode-20200725.1307`

**Comment by deb75** [comment]
I reinstalled `dap-mode` and indeed, it works now without inhibiting anything.

Regards
