### ISSUE TITLE
Debugpy and pytest

### ISSUE THREAD

**Issue by lccambiaghi** [emacs-lsp/dap-mode#396]
Hi, can you help me register a debug-template that allows me to debug a `pytest` function with `debugpy`?

What I can do now is to write
```
if __name__ == "__main__":
    test_blablabla()
```
and use this template:
```
(dap-register-debug-template "dap-debug-script"
                               (list :type "python"
                                     :args []
                                     :request "launch"
                                     :debugger 'debugpy
                                     :name "dap-debug-script"))
```

I tried to use the provided function `dap-python--debug-test-at-point` but I get an error:
```
dap-python--test-at-point: Wrong type argument: hash-table-p, nil
```

**Comment by nbfalcon** [comment]
`dap-python--test-at-point` is broken. I'll see if I can fix it now.

**Comment by nbfalcon** [comment]
FYI, the correct way is to just use `dap-debug` and to then select debug pytest (at point).

**Comment by nbfalcon** [comment]
I at least found the issue: https://github.com/emacs-lsp/lsp-mode/pull/2131 made `lsp--get-workspace-symbols` return DocumentSymbols instead of the old SymbolInformation, which dap-python relies on, causing `dap-python--parse-lsp-symbol` to fail.

**Comment by nbfalcon** [comment]
I have pushed a fix to master. Please try again.

**Comment by lccambiaghi** [comment]
Now I get:
```
Warning (emacs): Initialize request failed: Invalid message: "program", "module", and "code" are mutually exclusive
```
Any way I can debug the `conf` used?

**Comment by nbfalcon** [comment]
Try the following:
```emacs-lisp
(dap-register-debug-template "Python :: Run pytest (at point)"
			     (list :type "python-test-at-point"
				   :args ""
				   :module "pytest"
				   :request "launch"
                                   :debugger 'ptvsd
				   :name "Python :: Run pytest (at point)"))
```

**Comment by lccambiaghi** [comment]
That works well! Now, how can I use `debugpy` instead? The console feature is what I would like to add to my workflow

**Comment by nbfalcon** [comment]
Great! debugpy support will need some additional changes, which I will probably implement some time today.

**Comment by nbfalcon** [comment]
Should be fixed in latest master, can you please confirm that it works and close the issue in that case? (with debugpy, that is).

**Comment by lccambiaghi** [comment]
When using the standard "pytest at point" target I still get:

```
Warning (emacs): Initialize request failed: Invalid message: "program", "module", and "code" are mutually exclusive Disable showing Disable logging
```

What is the template I should use?

**Comment by nbfalcon** [comment]
That should be fixed with emacs-lsp/dap-mode#29d0c87.

**Comment by lccambiaghi** [comment]
Unfortunately, I still get the same error. Thank you for trying to help me, I appreciate it a lot! Keep trying please :D Anything I can do to help you?

**Comment by nbfalcon** [comment]
Try upgrading again, because from interacting with `dap-python--populate-test-at-point` in *scratch* I could conclude that it works correctly (:program is removed). If that issue persists, do `M-x trace-function RET dap-python--populate-test-at-point`, try again and show me the contents of the trace buffer. Also, try restarting Emacs.

**Comment by lccambiaghi** [comment]
Here is the trace:
```
1 -> (dap-python--populate-test-at-point (:type "python-test-at-point" :args "" :module "pytest" :request "launch" :name "Python :: Run pytest (at point)"))
1 <- dap-python--populate-test-at-point: (:type "python-test-at-point" :module "pytest" :request "launch" :name "Python :: Run pytest (at point)" :args ("blabla_test.py::test_summarize") :cwd "blabla" :program "blabla_test.py" :dap-server-path ("/Users/luca/Library/Caches/pypoetry/virtualenvs/caf-Rmt144RL-py3.7/bin/python" "-m" "debugpy.adapter"))
```

**Comment by nbfalcon** [comment]
I see the issue.

**Comment by nbfalcon** [comment]
Reopen if you still cannot debug tests.

**Comment by nbfalcon** [comment]
I'll use a dedicated branch for such things next time... Also, if this still doesn't work, please provide me with a pytest-repo so I can test locally.

**Comment by lccambiaghi** [comment]
I now get this other error:
```
../../../Library/Caches/pypoetry/virtualenvs/caf-Rmt144RL-py3.7/lib/python3.7/site-packages/_pytest/main.py:537: in _collect
    assert not names, "invalid arg {!r}".format((argpath, names))
E   AssertionError: invalid arg (local('/Users/luca/git/wondercast/caf'), ['test_summarize'])
=========================== short test summary info ============================
ERROR  - AssertionError: invalid arg (local('/Users/luca/git/wondercast/caf')...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.41s ===============================
```

`('/Users/luca/git/wondercast/caf')` is my working directory and `['test_summarize']` is my target test at point.. 

This is the trace output:
```
1 <- dap-python--populate-test-at-point: (:type "python-test-at-point" :module "pytest" :request "launch" :name "Python :: Run pytest (at point)" :cwd "/Users/luca/git/wondercast/caf" :args ("::test_summarize") :dap-server-path ("/Users/luca/Library/Caches/pypoetry/virtualenvs/caf-Rmt144RL-py3.7/bin/python" "-m" "debugpy.adapter"))
```
It seems that the target script where the test is located is missing?

BTW, the `ptvsd` you posted earlier now also broke, with a similar error.

**Comment by nbfalcon** [comment]
This one was easy for once. During the last commit, I accidentally removed the (buffer-file-name) from the test target. Everything *should* now work.

**Comment by lccambiaghi** [comment]
Yes!! That worked!! Awesome, thank you so much 💯
